[odoo_servers]
odoo-prod ansible_host="{{ vault_server_host }}" ansible_user=root

[odoo_servers:vars]
ansible_python_interpreter=/usr/bin/python3

# Add staging if needed
# [odoo_staging]
# odoo-stage ansible_host="{{ vault_server_host }}" ansible_user=root

# [all:children]
# odoo_servers
# odoo_staging
